name: 16s-phylo
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - biopython
  - ete3
  - plotly
  - pandas
  - mafft
  - iqtree
  - requests
  - tqdm
  - pip
  - pip:
      - kaleido  # for static image export
